---
title: "01: time series"
output: html_document
date: 'r Sys.Date()'
editor_options: 
  chunk_output_type: inline
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tidymodels)
library(modeltime)
library(lubridate)
library(timetk)

theme_set(theme_bw())

data_url <- "https://raw.githubusercontent.com/DiabbZegpi/AI-eval2/main/datos_precios_train.csv"
data <- read_csv(data_url) |> 
  mutate(Fecha = as_date(Fecha, format = "%d-%m-%Y")) |> 
  arrange(Fecha)

split <- initial_time_split(data, prop = 0.75)
train_data <- training(split)
test_data <- testing(split)

folds <- time_series_cv(
  train_data,
  date_var = Fecha,
  initial = 200,
  assess = 50,
  skip = 50,
  cumulative = TRUE
)

# folds <- rolling_origin(
#   train_data, 
#   initial = 200, 
#   assess = 50, 
#   cumulative = TRUE, 
#   skip = 50
# )
```

```{r}
folds |> 
  tk_time_series_cv_plan() |> 
  ggplot(aes(Fecha, Ultimo, color = .key)) +
  geom_line() +
  facet_wrap(~.id)
```

```{r}
train_data |> 
  mutate(ultimo_lag = Ultimo - lag(Ultimo),
         ultimo_lag_s = Ultimo - lag(Ultimo, n = 5),
         ultimo_lag_c = ultimo_lag - lag(ultimo_lag, n = 5)) |>
  pivot_longer(contains("ultimo_lag")) |> 
  ggplot(aes(Fecha, value)) +
  geom_line() +
  facet_wrap(~name, ncol = 1)
```

## *ARIMA model specification*

```{r}
arima_spec <- arima_reg(
  seasonal_period = 5,
  non_seasonal_differences = 1,
  seasonal_differences = 0,
  non_seasonal_ar = tune(), 
  non_seasonal_ma = tune(), 
  seasonal_ar = tune(), 
  seasonal_ma = tune()
) |> 
  set_engine("arima")


arima_grid <- crossing(
  non_seasonal_ar = 0:2,
  non_seasonal_ma = 0:2,
  seasonal_ar = 0:2,
  seasonal_ma = 0:2
)

arima_ultimo_rec <- recipe(Ultimo ~ Fecha, data = train_data)
arima_maximo_rec <- recipe(Maximo ~ Fecha, data = train_data)
arima_minimo_rec <- recipe(Minimo ~ Fecha, data = train_data)
```

```{r}
parallel_start(parallel::detectCores(logical = FALSE))

arima_ultimo_res <- tune_grid(
  workflow() |> add_model(arima_spec) |> add_recipe(arima_ultimo_rec), 
  resamples = folds, 
  grid = arima_grid, 
  metrics = metric_set(yardstick::mase, yardstick::rmse),
  control = control_grid(save_pred = TRUE)
)

arima_maximo_res <- tune_grid(
  workflow() |> add_model(arima_spec) |> add_recipe(arima_maximo_rec), 
  resamples = folds, 
  grid = arima_grid, 
  metrics = metric_set(yardstick::mase, yardstick::rmse),
  control = control_grid(save_pred = TRUE)
)

arima_minimo_res <- tune_grid(
  workflow() |> add_model(arima_spec) |> add_recipe(arima_minimo_rec), 
  resamples = folds, 
  grid = arima_grid, 
  metrics = metric_set(yardstick::mase, yardstick::rmse),
  control = control_grid(save_pred = TRUE)
)

parallel_stop()
```

```{r}
arima_minimo_res |> 
  collect_metrics() |> 
  pivot_longer(all_of(1:4)) |> 
  ggplot(aes(value, mean)) +
  geom_point(aes(color = .metric)) +
  scale_x_continuous(breaks = 0:2) +
  facet_wrap(~name)
```

## *Finalize ARIMA models*

```{r}
best_arima_ultimo <- arima_ultimo_res |> select_best("rmse")
best_arima_maximo <- arima_maximo_res |> select_best("rmse")
best_arima_minimo <- arima_minimo_res |> select_best("rmse")
```

```{r}
arima_ultimo <- workflow() |> 
  add_model(arima_spec) |> 
  add_recipe(arima_ultimo_rec) |> 
  finalize_workflow(best_arima_ultimo)

arima_maximo <- workflow() |> 
  add_model(arima_spec) |> 
  add_recipe(arima_maximo_rec) |> 
  finalize_workflow(best_arima_maximo)

arima_minimo <- workflow() |> 
  add_model(arima_spec) |> 
  add_recipe(arima_minimo_rec) |> 
  finalize_workflow(best_arima_minimo)
```

```{r}
predictions <- tibble(
  Fecha = test_data$Fecha,
  last_fit(arima_ultimo, split) |> collect_predictions() |> select(Ultimo = .pred),
  last_fit(arima_maximo, split) |> collect_predictions() |> select(Maximo = .pred),
  last_fit(arima_minimo, split) |> collect_predictions() |> select(Minimo = .pred)
)

test_data |>
  mutate(set = "truth") |> 
  bind_rows(predictions |> mutate(set = "preds")) |> 
  pivot_longer(all_of(2:4)) |> 
  ggplot(aes(Fecha, value, color = set)) +
  geom_line() +
  facet_wrap(~name)
```

## *Write submission*

```{r}
submission_url <- "https://raw.githubusercontent.com/DiabbZegpi/AI-eval2/main/datos_precio_prediction.csv"
submission_sample <- read_csv(submission_url) |> 
  mutate(Fecha = as_date(Fecha, format = "%d-%m-%Y"))

submission_sample$Ultimo <- arima_ultimo |> 
  fit(train_data) |> 
  predict(new_data = submission_sample) |> 
  pull(1)

submission_sample$Maximo <- arima_maximo |> 
  fit(train_data) |> 
  predict(new_data = submission_sample) |> 
  pull(1)

submission_sample$Minimo <- arima_minimo |> 
  fit(train_data) |> 
  predict(new_data = submission_sample) |> 
  pull(1)

submission_sample$Fecha <- format(submission_sample$Fecha, "%d-%m-%Y")
filename <- paste0("../Submissions/", Sys.Date(), "_ARIMA.csv")
write_csv(submission_sample, file = filename)
```

```{r}
submission_sample |> 
  pivot_longer(all_of(2:4)) |> 
  ggplot(aes(Fecha, value, color = name)) +
  geom_line()

submission_sample <- submission_sample |> 
  rowwise() |> 
  mutate(Ultimo = if_else(Ultimo > Maximo, Maximo, Ultimo))

submission_sample$Fecha <- format(submission_sample$Fecha, "%d-%m-%Y")
filename <- paste0("../Submissions/", Sys.Date(), "_ARIMA_MAX_corrected.csv")
write_csv(submission_sample, file = filename)
```


# ARIMA with log transform

```{r}
train_data_log <- train_data |> 
  mutate(across(where(is.numeric), log))

log_folds <- time_series_cv(
  train_data_log,
  date_var = Fecha,
  initial = 200,
  assess = 50,
  skip = 50,
  cumulative = TRUE
)

arima_ultimo_rec_log <- recipe(Ultimo ~ Fecha, data = train_data_log) 
arima_maximo_rec_log <- recipe(Maximo ~ Fecha, data = train_data_log)
arima_minimo_rec_log <- recipe(Minimo ~ Fecha, data = train_data_log)

ultimo_wf_log <- workflow() |> 
  add_model(arima_spec) |> 
  add_recipe(arima_ultimo_rec_log)

maximo_wf_log <- workflow() |> 
  add_model(arima_spec) |> 
  add_recipe(arima_maximo_rec_log)

minimo_wf_log <- workflow() |> 
  add_model(arima_spec) |> 
  add_recipe(arima_minimo_rec_log)
```

## *Tune grid*

```{r}
parallel_start(parallel::detectCores(logical = FALSE))

arima_ultimo_res_log <- tune_grid(
  ultimo_wf_log, 
  resamples = log_folds, 
  grid = arima_grid, 
  metrics = metric_set(yardstick::mase, yardstick::rmse),
  control = control_grid(save_pred = TRUE)
)

arima_maximo_res_log <- tune_grid(
  maximo_wf_log,
  resamples = log_folds, 
  grid = arima_grid, 
  metrics = metric_set(yardstick::mase, yardstick::rmse),
  control = control_grid(save_pred = TRUE)
)

arima_minimo_res_log <- tune_grid(
  minimo_wf_log,
  resamples = log_folds, 
  grid = arima_grid, 
  metrics = metric_set(yardstick::mase, yardstick::rmse),
  control = control_grid(save_pred = TRUE)
)

parallel_stop()
```

```{r}
best_arima_ultimo_log <- arima_ultimo_res_log |> select_best("rmse")
best_arima_maximo_log <- arima_maximo_res_log |> select_best("rmse")
best_arima_minimo_log <- arima_minimo_res_log |> select_best("rmse")
```

## *Finalize workflow*

```{r}
arima_ultimo_log <- finalize_workflow(ultimo_wf_log, best_arima_ultimo) |> fit(train_data_log)
arima_maximo_log <- finalize_workflow(maximo_wf_log, best_arima_maximo) |> fit(train_data_log)
arima_minimo_log <- finalize_workflow(minimo_wf_log, best_arima_minimo) |> fit(train_data_log)
```

## *Make submissions*

```{r}
submission_sample <- read_csv(submission_url) |> 
  mutate(Fecha = as_date(Fecha, format = "%d-%m-%Y"))

submission_sample$Ultimo <- predict(arima_ultimo_log, new_data = submission_sample) |> 
  pull(1) |> 
  exp()

submission_sample$Maximo <- predict(arima_maximo_log, new_data = submission_sample) |> 
  pull(1) |>
  exp()

submission_sample$Minimo <- predict(arima_minimo_log, new_data = submission_sample) |> 
  pull(1) |> 
  exp()

submission_sample$Fecha <- format(submission_sample$Fecha, "%d-%m-%Y")

filename <- paste0("../Submissions/", Sys.Date(), "_ARIMA_log.csv")
write_csv(submission_sample, file = filename)
```


```{r}
submission_sample2 <- submission_sample |> 
  rowwise() |> 
  mutate(Ultimo = if_else(Ultimo > Maximo, Maximo, Ultimo)) |> 
  ungroup()

filename <- paste0("../Submissions/", Sys.Date(), "_ARIMA_log_MAX_corrected.csv")
write_csv(submission_sample, file = filename)
```


# ARIMA-boost

```{r}
arima_xgb_spec <- arima_boost(
  seasonal_period = 5,
  non_seasonal_differences = 1,
  seasonal_differences = 1,
  non_seasonal_ar = tune(),
  non_seasonal_ma = tune(),
  seasonal_ar = tune(),
  seasonal_ma = tune(),
  mtry = tune(),
  trees = tune(),
  min_n = tune(),
  tree_depth = tune(),
  learn_rate = tune()
) |> 
  set_engine("arima_xgboost")

ultimo_rec <- recipe(Ultimo ~ Fecha, data = train_data) |> 
  step_timeseries_signature(Fecha) |> 
  step_rm(contains("xts"), contains("hour"), contains("minute"), contains("second")) |> 
  step_fourier(Fecha, period = 5, K = 3) |> 
  step_corr(all_numeric_predictors(), threshold = 0.8) |> 
  step_dummy(all_nominal_predictors())

maximo_rec <- recipe(Maximo ~ Fecha, data = train_data) |> 
  step_timeseries_signature(Fecha) |> 
  step_rm(contains("xts"), contains("hour"), contains("minute"), contains("second")) |> 
  step_fourier(Fecha, period = 5, K = 3) |> 
  step_corr(all_numeric_predictors(), threshold = 0.8) |> 
  step_dummy(all_nominal_predictors())

minimo_rec <- recipe(Minimo ~ Fecha, data = train_data) |> 
  step_timeseries_signature(Fecha) |> 
  step_rm(contains("xts"), contains("hour"), contains("minute"), contains("second")) |> 
  step_fourier(Fecha, period = 5, K = 3) |> 
  step_corr(all_numeric_predictors(), threshold = 0.8) |> 
  step_dummy(all_nominal_predictors())

ultimo_wf <- workflow() |> 
  add_model(arima_xgb_spec) |> 
  add_recipe(ultimo_rec)

maximo_wf <- ultimo_wf |> update_recipe(maximo_rec)
minimo_wf <- ultimo_wf |> update_recipe(minimo_rec)
```

```{r}
set.seed(1234)
grid_arima_xgb <- grid_random(
  non_seasonal_ar(range = c(0L, 3L)),
  non_seasonal_ma(range = c(0L, 3L)),
  seasonal_ar(),
  seasonal_ma(),
  mtry(range = c(5L, 30L)),
  trees(range = c(50L, 300L)),
  min_n(),
  tree_depth(),
  learn_rate(range = c(-5, -1)), 
  size = 100
)
```

```{r}
parallel_start(parallel::detectCores(logical = FALSE))

ultimo_res <- tune_grid(
  ultimo_wf, 
  resamples = folds, 
  grid = grid_arima_xgb, 
  metrics = metric_set(yardstick::mase, yardstick::rmse)
)

maximo_res <- tune_grid(
  maximo_wf,
  resamples = folds, 
  grid = grid_arima_xgb, 
  metrics = metric_set(yardstick::mase, yardstick::rmse)
)

minimo_res <- tune_grid(
  minimo_wf,
  resamples = folds, 
  grid = grid_arima_xgb, 
  metrics = metric_set(yardstick::mase, yardstick::rmse)
)

parallel_stop()
```

```{r fig.width=11}
bind_rows(
  collect_metrics(ultimo_res) |> mutate(target = "Ultimo"),
  collect_metrics(maximo_res) |> mutate(target = "Maximo"),
  collect_metrics(minimo_res) |> mutate(target = "Minimo")
) |> 
  pivot_longer(all_of(1:9)) |>
  filter(.metric == "rmse") |> 
  ggplot(aes(value, mean ^ 2)) +
  geom_point(aes(color = target)) +
  facet_wrap(~name, scales = "free_x")
```

```{r}
final_wf_ultimo <- finalize_workflow(ultimo_wf, select_best(ultimo_res, metric = "rmse"))
final_wf_maximo <- finalize_workflow(maximo_wf, select_best(maximo_res, metric = "rmse"))
final_wf_minimo <- finalize_workflow(minimo_wf, select_best(minimo_res, metric = "rmse"))

ultimo_lf <- last_fit(final_wf_ultimo, split)
maximo_lf <- last_fit(final_wf_maximo, split)
minimo_lf <- last_fit(final_wf_minimo, split)

submission_url <- "https://raw.githubusercontent.com/DiabbZegpi/AI-eval2/main/datos_precio_prediction.csv"
submission_sample <- read_csv(submission_url) |> 
  mutate(Fecha = as_date(Fecha, format = "%d-%m-%Y"))

submission_sample$Ultimo <- predict(ultimo_lf |> extract_workflow(), new_data = submission_sample) |> pull(.pred)
submission_sample$Maximo <- predict(maximo_lf |> extract_workflow(), new_data = submission_sample) |> pull(.pred)
submission_sample$Minimo <- predict(minimo_lf |> extract_workflow(), new_data = submission_sample) |> pull(.pred)
submission_sample$Fecha <- format(submission_sample$Fecha, "%d-%m-%Y")

filename <- paste0("../Submissions/", Sys.Date(), "_ARIMA_XGBoost.csv")
write_csv(submission_sample, file = filename)
```

## *Correct predictions by boundaries*

```{r}
submission_sample |> 
  pivot_longer(where(is.numeric)) |> 
  ggplot(aes(dmy(Fecha), value, color = name)) +
  geom_line()
```

```{r}
submission_sample_c <- submission_sample |> 
  rowwise() |> 
  mutate(Ultimo = median(Minimo, Maximo)) |> 
  ungroup()

filename <- paste0("../Submissions/", Sys.Date(), "_ARIMA_XGBoost_Corrected.csv")
write_csv(submission_sample, file = filename)
```

